title: Julian Reif
description: My Github website
author: Julian Reif
logo: /assets/reif.jpg
github: https://github.com/reifjulian
about: Assistant Professor of Finance and Economics
description: > # this means to ignore newlines until "baseurl:"
    This is my GitHub website
baseurl: ""
url: https://reifjulian.github.io/

allowsearch: true

github_username: reifjulian

share:
  twitter_username: julianreif
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "blog/page:num/"
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-numbered-headings]

